apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: snaka/webapp:87ca400
          command: ["/bin/bash", "./setup.sh"]
          env:
            - name: PASSENGER_APP_ENV
              value: development
      restartPolicy: Never
