service: auth-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

# plugins:
#   - '@silvermine/serverless-plugin-cloudfront-lambda-edge'

package:
  include:
    - node_modules/*

functions:
  edge:
    handler: handler.hello
    memorySize: 128
    timeout: 1
  api:
    handler: api.hoge
    memorySize: 128
    timeout: 10
