# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca0e7b62a57d1dc63b2f25b7bddc6da62184520416b3279ebbc9d88ed5e393a0aada9a22ea245d89ca56cb5a14b548ccd4fb822357b461b199694a536df9c07

test:
  secret_key_base: 36877010a764c1563edea306e9568593581d2d89618254fb8dc51f5e9d890abe8978f50b070dd50f5a1a323d62adcca30a44b5e3be4fad383fefa19077782711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
