AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cf-viewer-request-handler
  Sample SAM Template for cf-viewer-request-handler

Resources:
  CFViewerRequestHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: viewer-request-handler/
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      Runtime: nodejs8.10
      Handler: app.lambdaHandler
      AutoPublishAlias: live

  LambdaEdgeFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"

Outputs:
  CFViewerRequestHandler:
    Description: "Lambda@Edge Function ARN"
    Value: !GetAtt CFViewerRequestHandlerFunction.Arn
